spring:
  config:
    import: optional:classpath:.env[.properties]

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: ConsumerHikariCP
      maximum-pool-size: 60
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 600000
      leak-detection-threshold: 10000

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate.globally_quoted_identifiers: true
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: Asia/Seoul
    defer-datasource-initialization: true

  batch:
    jdbc:
      initialize-schema: always

  sql:
    init:
      mode: always
      encoding: UTF-8
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

management:
  endpoints:
    web:
      exposure:
        include: prometheus